In [42]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity

In [43]:
from icecream import ic

In [44]:
person1 = [85,34,123,54]

In [45]:
mood = ['happy','sad','peace','amazed']

In [46]:
import numpy as np

In [47]:
w = np.random.randn(4, 5)
ic(w)

ic| w: array([[ 1.8296597 , -0.19390443,  1.72973537,  0.03256374,  1.05268859],
              [ 3.12170242, -0.88979672, -0.95542295, -1.28200127, -0.34318877],
              [ 1.06562649,  0.63735527, -1.35065266, -1.32702311, -1.11605897],
              [-1.25801853,  0.02546081, -0.65251171, -1.34217111,  0.85375435]])


array([[ 1.8296597 , -0.19390443,  1.72973537,  0.03256374,  1.05268859],
       [ 3.12170242, -0.88979672, -0.95542295, -1.28200127, -0.34318877],
       [ 1.06562649,  0.63735527, -1.35065266, -1.32702311, -1.11605897],
       [-1.25801853,  0.02546081, -0.65251171, -1.34217111,  0.85375435]])

In [48]:
b = np.random.random()
ic(b)

ic| b: 0.805560735013279


0.805560735013279

In [49]:
logits = np.dot(person1, w) + b
ic(logits)

ic| logits: array([ 325.60357528,   33.84017693,  -86.01722275, -275.71564668,
                    -12.55684495])


array([ 325.60357528,   33.84017693,  -86.01722275, -275.71564668,
        -12.55684495])

In [50]:
def softmax(x):
    x -= np.max(x)
    return np.exp(x)/np.sum(np.exp(x))

In [51]:
predicted1 = softmax(logits)
ic(predicted1)

ic| predicted1: array([1.00000000e+000, 1.94431252e-127, 1.71932816e-179, 7.08565562e-262,
                       1.37656110e-147])


array([1.00000000e+000, 1.94431252e-127, 1.71932816e-179, 7.08565562e-262,
       1.37656110e-147])

In [52]:
label1 = [0, 1, 0, 0]

In [53]:
another_predicted1 = [.1, .8, .05, .05]

In [54]:
def cross_entropy(label, predicted):
    return -sum(label[i]*np.log(predicted[i]) for i in range(len(label)))

In [55]:
cross_entropy(label1, predicted1)

291.76339835660707

In [56]:
cross_entropy(label1, another_predicted1)

0.2231435513142097